#!/bin/sh

remove_statoverride() {
	path="$1"

	if dpkg-statoverride --list "$path" >/dev/null 2>&1; then
		dpkg-statoverride --remove "$path"
	fi
}

main() {
	action="$1"

	# don't remove stat overrides if not uninstalling
	if [ "$action" != "remove" ]; then
		return 0
	fi

	remove_statoverride "/var/lib/toolbox/uipc/pubsub"
	remove_statoverride "/var/lib/toolbox/uipc/priv"
	remove_statoverride "/var/lib/toolbox/uipc/pub"
	remove_statoverride "/var/lib/toolbox/uipc"
	remove_statoverride "/var/lib/toolbox/ipc/pubsub"
	remove_statoverride "/var/lib/toolbox/ipc/priv"
	remove_statoverride "/var/lib/toolbox/ipc/pub"
	remove_statoverride "/var/lib/toolbox/ipc"
	remove_statoverride "/var/lib/toolbox"

	delgroup toolbox
	delgroup toolbox_ipc

	return 0
}

{
	main "$@"
	exit "$?"
}
