#!/bin/sh

main() {
	action="$1"

	# only add groups and stat overrides when installing
	if [ "$action" != "configure" ]; then
		return 0
	fi

	# If a group exists, there is a chance that the user
	# has customized directory ownership and permissions,
	# so we don't change it.

	if addgroup toolbox; then
		if ! dpkg-statoverride --list /var/lib/toolbox >/dev/null 2>&1; then
			dpkg-statoverride --update --add root toolbox 0770 /var/lib/toolbox
		fi
	fi

	if addgroup toolbox_ipc; then
		if ! dpkg-statoverride --list /var/lib/toolbox/ipc >/dev/null 2>&1; then
			dpkg-statoverride --update --add root toolbox_ipc 2770 /var/lib/toolbox/ipc
		fi

		if ! dpkg-statoverride --list /var/lib/toolbox/uipc >/dev/null 2>&1; then
			dpkg-statoverride --update --add root toolbox_ipc 2770 /var/lib/toolbox/uipc
		fi
	fi

	return 0
}

{
	main "$@"
	exit "$?"
}
